### ISSUE TITLE
volunteer list

### ISSUE THREAD

**Issue by sandikbarr** [mysterycodesociety/mcs-web#4]
Volunteers should be those who have worked with us since Mystery Code Society beginning with htmelle fall 2017.

Grace Erixon
Hailey Gillespie
Trisha Gawley
Lauren Koperski
Jen Homann
Aryani Roy
Nasteho Mohamud
Cara Heacock
Andrew Yolland
Emma Buckley

Alexandra Millatmal - are we listing CoC separately or with volunteers?
Bianca Zongrone - same question for advisory board members, separate or with volunteers

**Comment by Gmfholley** [comment]
I vote for advisory & CoC members to be with board members instead of volunteers.

That list looks right to me.

**Comment by sandikbarr** [comment]
pushed to https://mysterycodesociety.github.io/mcs-web/volunteer.html
