### ISSUE TITLE
sponsors who have support us

### ISSUE THREAD

**Issue by sandikbarr** [mysterycodesociety/mcs-web#6]
Supporting sponsors and logos will be shown on the Sponsors page.

The leading text will say:

> We could not done what we have done without the generosity of our sponsors, and we will not be able to achieve all we want to achieve without partnering with more sponsors in the future. And we do feel our sponsors are partners with us in this mission. Sponsors visit our classes, come to our graduations, connect us with community leaders who connect us with more students. 
> 
> Our current sponsors include:

* **Our Location Sponsor, the Milton R. Abrahams Library**: Since the beginning we have partnered with this branch of the Omaha Public Library on 90th and Fort Street. They have donated not just the space where we hold their class, but the support of their incredible staff, Chrome Books for the students to learn on, and a platform to find new students who may not have heard of us any other way.
* **Our Pizza Sponsor, Dynamo**: Dynamo is an Omaha based IT consulting and recruiting firm, and since the very first class they have provided lunch for all our students and teaching assistants. While pizza may seem like a perk, providing lunch helps students focus, and keeps us accessible for students who might not otherwise be able to take the class.
* **Our Technology Sponsor, AIM/Interface Web School**: AIM is an innovative not-for-profit community organization that grows, connects and inspires the community through technology; and sadly, access to technology is one of the biggest barriers between students and code. AIM has generously donated laptops, set up with the programs needed to teach the students languages and frameworks we never had the technological oomph to tackle before.
* **Our Graduation Sponsor, ACMW and Dynamo**: Our graduation ceremonies are a chance for students and their families to come together and celebrate all they’ve accomplished, and is one of our favorite parts of each class. This WordPress hosting company sponsored this fall’s graduation with snacks, swag, and decorations worthy of the coder’s hard work.

**Comment by sandikbarr** [comment]
The text on Flywheel saying they sponsored "this fall's graduation" makes it seem as though it is upcoming since it is now summer.

**Comment by sandikbarr** [comment]
UNO ACM-W should be added to this list as a graduation sponsor.

**Comment by sandikbarr** [comment]
pushed to https://mysterycodesociety.github.io/mcs-web/sponsor.html

**Comment by sandikbarr** [comment]
Agape & Farm Credit for graduation space?

**Comment by bellicapax** [comment]
Were we only doing those sponsors that were within the last year? If so, Agape makes that cut but I don't think Farm Credit does? (I can't exactly remember timelines, though)

**Comment by sandikbarr** [comment]
I _think_ since Mystery Code Society was made official in February? which yeah, Farm Credit hosted that htmelle masters graduation.

**Comment by bellicapax** [comment]
Ah! My bad. Those two are good then from my standpoint. 👍

**Comment by sandikbarr** [comment]
per 10/15 quarterly meeting, Farm Credit does not "do it for the credit" and doesn't want to be on the site.

**Comment by sandikbarr** [comment]
ACM-W logo
![acmw sticker 1](https://user-images.githubusercontent.com/2250413/47024065-985d1680-d126-11e8-9f16-27e35d1fe32d.png)

Shannon should be getting us the Agape logo.

We also need descriptions for these sponsors.

**Comment by Gmfholley** [comment]
Dynamo is also a graduatio sponsor.
