### ISSUE TITLE
sponsor asks

### ISSUE THREAD

**Issue by sandikbarr** [mysterycodesociety/mcs-web#7]
Sponsor "Big Asks" cards will be shown at the top section of the sponsors page.

Leading text:

> While our curriculum is designed challenge the minds of our students, there are some puzzles we don’t want them to have to solve. One of our core values has always been accessibility, and some of the barriers to getting into code have nothing to do with the code itself: lack of access to technology, transportation, or even an empty stomach can stand between a potential coder and their ambition to learn. We do not charge our students any kind of tuition, so it is only through the support of our generous sponsors that we are able to continue with our vision.

* **Pizza Sponsor**
(one needed per class)
While pizza may seem like a perk, providing lunch helps students focus, and keeps us accessible for students who might not otherwise be able to take the class.

* **Location Sponsor**
(one needed per class)
Monetary or donation of space
A regular home base that’s accessible to our students (with reliable wifi!) takes a lot of the guesswork out for our organizers (and the parents of our students!)

* **Graduation Sponsor**
(one needed per full class)
Snacks, decorations and awards for our Graduation Celebrations, one of the most rewarding days of class for students, their families, and our volunteers.

* **Snack Sponsor**
(one needed per class)
Light snacks are provided every week. 
Sometimes fruit snacks are just the break you need to fix that bug.

Follow "big ask" cards with this text:
> All sponsors are featured on our website, as well as getting frequent shout outs from the MCS social media, and an invitation to our Graduation Celebrations. Full Course Sponsors and Cornerstone Sponsors (Technology, Location, and Pizza Sponsors) get individual posts thanking them on our MCS facebook. Mystery Code Society is a registered 501(c)(3) and donations are tax deductible. Any sponsor donating over $250 will receive official documentation of the donation in their thank you letter.
> 
> Excited by our mission, but not sure how you can help us grow? Please contact us at mysterycodesociety@gmail.com and one of our board members will contact you to discuss how we can work together to close the equity gap in tech.

**Comment by sandikbarr** [comment]
are we listing prices on the website?

**Comment by sandikbarr** [comment]
What was the decision about half course sponsorships for pizza, location and snacks? I'd rather not do half course sponsors as a project lead, it means I've got to do twice the work to line up sponsors, and it will change mid class when we're the most busy.

**Comment by Gmfholley** [comment]
I say let's keep it simple.  Let's not offer half course sponsorships on the website and take those on a case by case basis.

I think some prices (for individual giving) would be good on the website.  It gives people an idea of where money goes and how they can help.  But for sponsor giving, I think we can do a 'Contact us' for now, and then share the prices that we have come up with?  thoughts?

**Comment by sandikbarr** [comment]
pushed to https://mysterycodesociety.github.io/mcs-web/sponsor.html
