### ISSUE TITLE
mission statement FAQ

### ISSUE THREAD

**Issue by sandikbarr** [mysterycodesociety/mcs-web#8]
"To champion gender equity in tech through beginner and intermediate  coding education for women, femmes, and non-men"

Mission Statement FAQ:
**What is gender equity?  Is that the same as equality?**
Equity is not equality.

Equity means giving enough for everyone be successful.  Equity does not mean equal or fair, but what is just, considering that distribution of privileges, rights, and access has not been equal for a long time. Equity might mean that underrepresented and marginalized groups need more than the currently privileged in order to be successful.

Gender equity means giving enough for people of all genders to be successful.

**What ages of students do you accept?**
Currently, most of our programs are aimed at students in 6th-12th grade, because we believe with our current resources, we can do the most good with students at that age.  But it may vary by program.

**Can nonbinary and trans students participate?**
We welcome nonbinary students.  Trans women are women, and we welcome women into our program.

**Why do you specify `women, femmes, and non-men`?  What is the difference?**
Because our aim is to achieve gender equity in tech, our organization is by and for anyone who does not receive privilege from their gender identity and/or expression (i.e. any group that does not currently have gender equity). 

This includes anyone (cis and trans) who identifies as a woman, men who identify as femme, and anyone who does not identify as a man (non-men), including nonbinary people and gender nonconforming people who prefer no labels or labels we have not mentioned.

Although some of these terms are overlapping, we want to make sure the students that we serve feel represented in our mission.

**Comment by sandikbarr** [comment]
I'm assuming mission is a separate page that we are adding.

**Comment by Gmfholley** [comment]
I think our mission is small enough to go in the navbar.  I often see the mission on the landing page for nonprofits.

But I think we could have a separate Mission page, which lists the mission at the top and has the mission FAQ.

Optionally, there could be a link from the Mission in the navbar to the complete Mission page, like, "Learn More!"

**Comment by sandikbarr** [comment]
Not sure if those are separate options listing the full mission in the navbar and on the mission page...
I put this together for the mission FAQ with the mission statement in the navbar
<img width="858" alt="screen shot 2018-07-19 at 3 02 13 pm" src="https://user-images.githubusercontent.com/2250413/42967092-c92a3b2e-8b64-11e8-92e8-353e22eff41b.png">

Were you also thinking of having the mission statement text on the mission FAQ page (and in the navbar)?

And then should the mission statement be removed from the landing page and just be in the navbar, or...?
<img width="855" alt="screen shot 2018-07-19 at 3 05 00 pm" src="https://user-images.githubusercontent.com/2250413/42967209-277b12ca-8b65-11e8-9ef6-03abf98aaca6.png">

**Comment by sandikbarr** [comment]
pushed to https://mysterycodesociety.github.io/mcs-web/
