### ISSUE TITLE
student projects

### ISSUE THREAD

**Issue by sandikbarr** [mysterycodesociety/mcs-web#9]
Student projects should be those that have been done with Mystery Code Society.

Remove SheQL, Sugar Cubed, Do Space, and Abrahams Branch 2016 projects.

Bring htmelle master projects over from OGCW.

**Comment by Gmfholley** [comment]
I think the student projects from our custom curriculum classes are good marketing.  They establish a track record.  And they are not really Girls Who Code.  I think we own them.

Is there value in keeping the projects from our custom classes?

That would add Sugar Cubed & SheQL to this list.

**Comment by sandikbarr** [comment]
so... I kind of thought I heard that the whole reason for keeping the omahagirlswhocode site going was for these projects that pre-existed MCS?

**Comment by sandikbarr** [comment]
Games for YOUnity projects to be added when ready

**Comment by mystery-code-society** [comment]
HTMelle Masters Projects

<img width="1910" alt="victoria" src="https://user-images.githubusercontent.com/34634196/56086006-3c442800-5e13-11e9-9aff-a6913236f2c1.png">
<img width="1917" alt="nikita" src="https://user-images.githubusercontent.com/34634196/56086007-3c442800-5e13-11e9-9261-48a79a3e7edc.png">
<img width="1918" alt="lauren" src="https://user-images.githubusercontent.com/34634196/56086008-3c442800-5e13-11e9-9276-ce48f7d5ce18.png">
<img width="1920" alt="neveah" src="https://user-images.githubusercontent.com/34634196/56086009-3c442800-5e13-11e9-9a23-e5c197ed539d.png">
<img width="1920" alt="jessica" src="https://user-images.githubusercontent.com/34634196/56086010-3c442800-5e13-11e9-86fc-09904898a24a.png">
<img width="1915" alt="jae" src="https://user-images.githubusercontent.com/34634196/56086011-3c442800-5e13-11e9-8f09-7770d519e689.png">
<img width="1917" alt="anjali" src="https://user-images.githubusercontent.com/34634196/56086012-3c442800-5e13-11e9-8d82-8779308491df.png">
<img width="1916" alt="jaleah" src="https://user-images.githubusercontent.com/34634196/56086013-3cdcbe80-5e13-11e9-9041-18710abc0696.png">

| Link | Project Name | Student Name |
| ---- | ------------- |--------------- |
| https://jessiemcs.github.io/whatevenareyou/ | Luigi | Jessica |
| https://laurenroberts.github.io/thisThing/ | This Thing | Lauren |
| https://nikitaluna.github.io/top-tech/ | Top Tech | Nikita |
| https://victoriach231.github.io/HTMelle-project/ | VC Bracelets | Victoria | 
| https://jcarter2590.github.io/fortnite/ | Fortnite | Ja'Leah |
| https://elmoandbailey.github.io/Elmo/ | Yeet | Neveah |
| https://anjalijayan415.github.io/MNGirlUp/ | MNGirlUp | Anjali |
| https://jewlsorthman.github.io/scabby-ghouls/ | Scabby Ghouls | Jae |

**Comment by mystery-code-society** [comment]
@mel-d We have One set of student projects that is ready to go up, whenever you have the time.

**Comment by alecdotninja** [comment]
I think there are other changes in scope for this issue (beyond adding the HTMelle Masters Projects), but I wasn't sure how to stop #59 for automatically closing it during the merge.

Reopening for now.

**Comment by mel-d** [comment]
Closing because @Gmfholley says she's going to open a new issue for the other class's projects.
